apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - quotas.yaml
  - namespace.yaml

namespace: test-replacements
configMapGenerator:
  - name: metas
    literals:
      - limits.cpu=16
      - limits.memory=24Gi

replacements:
  - source:
      kind: ConfigMap
      name: metas
      fieldPath: data.[limits.memory]
    targets:
      - select:
          name: common
          kind: ResourceQuota
        fieldPaths:
          - spec.hard.[limits.memory]
  - source:
      kind: ConfigMap
      name: metas
      fieldPath: data.[limits.cpu]
    targets:
      - select:
          name: common
          kind: ResourceQuota
        fieldPaths:
          - spec.hard.[limits.cpu]
