apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - quotas.yaml
  - namespace.yaml
  - configmap.yaml

namespace: test-replacements
#configMapGenerator:
#  - name: metas
#    literals:
#      - limits.cpu=16
#      - limits.memory=24Gi

transformers:
  - replacement-transformer.yaml
  - annotations-transformer.yaml
